#! /usr/bin/env bash
set -e
[ -n "$TMUXIFIER_DEBUG" ] && set -x

# Load internal utility functions.
source "$TMUXIFIER/lib/util.sh"

# Provide tmuxifier help
if calling-help "$@"; then
  echo "usage: tmuxifier load-session <layout_name | file_path> [<iterm mode>] [<session name>]

Aliases: session, ses, s

Create a session using the session layout, unless the session already exists
in which case, we simply attach/switch to the existing one.

Arguments:
   <layout_name | file_path>  - Name of a session layout stored in the layouts
                                directory, or path to a session layout file.
   <iterm mode>               - When given as \"-CC\" tmux will be called with
                                the -CC argument enabling iTerm2 integration.
                                More info: https://iterm2.com
   <session name>             - When given, overrides the name of the new session
                                to be <session name>."
  exit
fi

# Provide tmuxifier completions
if calling-complete "$@"; then
  tmuxifier-list-sessions
  exit
fi

if [ -z "$1" ]; then
  echo "$(tmuxifier-help load-session $@)" >&2
  exit 1
fi

# Load runtime functions.
source "$TMUXIFIER/lib/runtime.sh"

# If -CC is in the argument list, set TMUXIFIER_TMUX_ITERM_ATTACH
# and then remove the argument from $@.
for arg
do
    shift
    if test "$arg" = "-CC"
    then
        export TMUXIFIER_TMUX_ITERM_ATTACH="-CC"
        continue
    fi
    set -- "$@" "$arg"
done

# Load session file.
load_session "$@"
