#! /usr/bin/env bash
set -e
[ -n "$TMUXIFIER_DEBUG" ] && set -x

# Load internal utility functions.
source "$TMUXIFIER/lib/util.sh"

# Provide tmuxifier help
if calling-help "$@"; then
  echo "usage: tmuxifier load-session <layout_name>

Aliases: session, ses, s

Create a session using the session layout, unless the session already exists
in which case, we simply attach/switch to the existing one."
  exit
fi

# Provide tmuxifier completions
if calling-complete "$@"; then
  for item in $(tmuxifier-list-sessions); do
    echo "$item"
  done
  exit
fi

if [ -z "$1" ]; then
  echo "$(tmuxifier-help load-session)" >&2
  exit 1
fi

# Load runtime functions.
source "$TMUXIFIER/lib/runtime.sh"

# Load session file.
load_session "$1"
