#! /usr/bin/env bash
set -e
[ -n "$TMUXIFIER_DEBUG" ] && set -x

# Provide tmuxifier help
if [ "$1" == "--help" ]; then
  echo "usage: tmuxifier list

Aliases: ls

List all available session and window layouts."
  exit
fi

echo ""
echo "Sessions:"
tmuxifier-list-sessions
echo ""
echo "Windows:"
tmuxifier-list-windows
echo ""
