#! /usr/bin/env bash
set -e
[ -n "$TMUXIFIER_DEBUG" ] && set -x

# Load internal utility functions.
source "$TMUXIFIER/lib/util.sh"

# Provide tmuxifier help
if calling-help "$@"; then
  echo "usage: tmuxifier tmux [...]

Wrapper command for Tmux executable allowing Tmuxifier to pass in any custom
arguments specified in the TMUXIFIER_TMUX_OPTS environment variable."
  exit
fi

tmux $TMUXIFIER_TMUX_OPTS "$@"
