#! /usr/bin/env bash
set -e
[ -n "$TMUXIFIER_DEBUG" ] && set -x

# Provide tmuxifier help
if [ "$1" == "--help" ]; then
  echo "usage: tmuxifier list

Aliases: ls

List all available session and window layouts."
  exit
fi

echo ""
echo "Sessions:"
for item in $(tmuxifier-list-sessions); do
  echo " - $item"
done
echo ""
echo "Windows:"
for item in $(tmuxifier-list-windows); do
  echo " - $item"
done
echo ""
