#! /usr/bin/env bash
set -e
[ -n "$TMUXIFIER_DEBUG" ] && set -x

# Load internal utility functions.
source "$TMUXIFIER/lib/util.sh"

# Provide tmuxifier help
if calling-help "$@"; then
  echo "usage: tmuxifier delete-session <layout_name>

Aliases: delete-ses, dses, ds

Permanently delete specified session layout."
  exit
fi

# Provide tmuxifier completions
if calling-complete "$@"; then
  tmuxifier-list-session
  exit
fi

if [ -z "$1" ]; then
  echo "$(tmuxifier-help delete-session $@)" >&2
  exit 1
fi

layout_name="$1"
layout_file="$TMUXIFIER_LAYOUT_PATH/${layout_name}.session.sh"

if [ ! -f "$layout_file" ]; then
  echo "tmuxifier: session layout '$layout_name' does not exist." >&2
  exit 1
fi

if rm -v --interactive "$layout_file" && [ -e "$layout_file" ]; then
  echo "tmuxifier: session layout '$layout_file' was not deleted." >&2
fi
