#! /usr/bin/env bash
set -e
[ -n "$TMUXIFIER_DEBUG" ] && set -x

# Provide tmuxifier help
if [ "$1" == "--help" ]; then
  echo "usage: tmuxifier version

Outputs Tmuxifier version."
  exit
fi

echo "0.5.1"
