#! /usr/bin/env bash
set -e
[ -n "$TMUXIFIER_DEBUG" ] && set -x

# Provide tmuxifier completions
if [ "$1" == "--complete" ]; then
  tmuxifier-commands
  exit
fi

has-completions() {
  grep -i "^# provide tmuxifier completions" "$1" >/dev/null
}

command="$1"
if [ -z "$command" ]; then
  echo "$(tmuxifier-help completions)" >&2
  exit 1
fi

! command_path="$(command -v "tmuxifier-$command")"

# Attempt to resolve aliases
if [ -z "$command_path" ]; then
  resolved="$(tmuxifier-alias "$command")"
  if [ ! -z "$resolved" ]; then
    ! command_path="$(command -v "tmuxifier-$resolved")"
  fi
fi

if [ ! -z "$command_path" ] && has-completions "$command_path"; then
  shift
  exec "$command_path" --complete "$@"
fi
