#! /usr/bin/env bash
set -e
[ -n "$TMUXIFIER_DEBUG" ] && set -x

# Provide tmuxifier help
if [ "$1" == "--help" ]; then
  echo "usage: tmuxifier alias <alias>

Resolve a command alias to it's full name."
  exit
fi

case "$1" in
  "session" | "ses" | "s" )
    echo "load-session"
    ;;
  "window" | "win" | "w" )
    echo "load-window"
    ;;
  "new-ses" | "nses" | "ns" )
    echo "new-session"
    ;;
  "new-win" | "nwin" | "nw" )
    echo "new-window"
    ;;
  "edit-ses" | "eses" | "es" )
    echo "edit-session"
    ;;
  "edit-win" | "ewin" | "ew" )
    echo "edit-window"
    ;;
  "l" )
    echo "list"
    ;;
  "list-ses" | "lses" | "ls" )
    echo "list-sessions"
    ;;
  "list-win" | "lwin" | "lw" )
    echo "list-windows"
    ;;
  * )
    exit 1
esac
