#! /usr/bin/env bash
set -e
[ -n "$TMUXIFIER_DEBUG" ] && set -x

# Provide tmuxifier help
if [ "$1" == "--help" ]; then
  echo "usage: tmuxifier list-sessions

Aliases: list-ses, lses, ls

List all session layouts."
  exit
fi

list=$(find -L "$TMUXIFIER_LAYOUT_PATH" -name "*.session.sh")
for file in $list; do
  file=${file/$TMUXIFIER_LAYOUT_PATH\//}
  echo "${file/.session.sh/}"
done
