#! /usr/bin/env bash
set -e
[ -n "$TMUXIFIER_DEBUG" ] && set -x

# Provide tmuxifier completions
if [ "$1" == "--complete" ]; then
  for item in $(tmuxifier-list-sessions); do
    echo "$item"
  done
  exit
fi

# Load runtime functions.
source "$TMUXIFIER/runtime.sh"

if [ ! -z $TMUX ]; then
  load_session "$1"
else
  echo "tmuxifier: 'load-session' command can only be used from within Tmux."
  exit 1
fi
