#! /usr/bin/env bash
set -e
[ -n "$TMUXIFIER_DEBUG" ] && set -x

# Provide tmuxifier help
if [ "$1" == "--help" ]; then
  echo "usage: tmuxifier current-session

Outputs the name of the current Tmux session."
  exit
fi

if [ -n "$TMUX" ]; then
  for item in $(tmux list-pane -F "#{session_name}");do
    echo $item
    exit 0
  done
fi

exit 1
