#! /usr/bin/env bash
set -e
[ -n "$TMUXIFIER_DEBUG" ] && set -x

if [ ! -z $TMUX ]; then
  for item in $(tmux list-sessions -F "#{?session_attached,1,0}:#S"); do
    if [[ "$item" == "1:"* ]]; then
      echo ${item/1:/}
      exit 0
    fi
  done
fi

exit 1
